# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AbZuDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AbZuDialog(object):
    def setupUi(self, AbZuDialog):
        AbZuDialog.setObjectName("AbZuDialog")
        AbZuDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        AbZuDialog.resize(364, 108)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\kursbuch.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AbZuDialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(AbZuDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AbZuDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.labelSname = QtWidgets.QLabel(AbZuDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSname.setFont(font)
        self.labelSname.setObjectName("labelSname")
        self.gridLayout.addWidget(self.labelSname, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.dateEdit = QtWidgets.QDateEdit(AbZuDialog)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(239, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButtonOK = QtWidgets.QPushButton(AbZuDialog)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_2.addWidget(self.pushButtonOK, 1, 1, 1, 1)

        self.retranslateUi(AbZuDialog)
        QtCore.QMetaObject.connectSlotsByName(AbZuDialog)

    def retranslateUi(self, AbZuDialog):
        _translate = QtCore.QCoreApplication.translate
        AbZuDialog.setWindowTitle(_translate("AbZuDialog", "Abgangs-/Wechseldatum"))
        self.label.setText(_translate("AbZuDialog", "Abgangs-/Wechseldatum setzten für:"))
        self.labelSname.setText(_translate("AbZuDialog", "Vorname, Nachname"))
        self.pushButtonOK.setText(_translate("AbZuDialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AbZuDialog = QtWidgets.QDialog()
    ui = Ui_AbZuDialog()
    ui.setupUi(AbZuDialog)
    AbZuDialog.show()
    sys.exit(app.exec_())
