# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BlockGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tutmodgui(object):
    def setupUi(self, Tutmodgui):
        Tutmodgui.setObjectName("Tutmodgui")
        Tutmodgui.setWindowModality(QtCore.Qt.ApplicationModal)
        Tutmodgui.resize(314, 294)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\kursbuch.ico"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tutmodgui.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Tutmodgui)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(Tutmodgui)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Tutmodgui)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 290, 242))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(30, 11, 30, 11)
        self.gridLayout.setObjectName("gridLayout")

        liste = [("Mo, 24.12. (1)", "e"),
                 ("Mo, 24.12. (2)", "e"),
                 ("Mo, 24.12. (3)", "u"),
                 ("Mo, 01.04. (1)", "u"),
                 ("Mo, 01.04. (2)", "u"),
                 ("Mo, 01.04. (3)", "u")]
        z = 0
        for i in liste:
            self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            self.label.setAlignment(
                QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
            self.label.setObjectName("label_" + str(z))
            self.gridLayout.addWidget(self.label, z, 0, 1, 1)
            self.button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
            sizePolicy = QtWidgets.QSizePolicy(
                QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(
                self.button.sizePolicy().hasHeightForWidth())
            self.button.setSizePolicy(sizePolicy)
            self.button.setMinimumSize(QtCore.QSize(40, 40))
            self.button.setMaximumSize(QtCore.QSize(40, 40))
            self.button.setText(i[1])
            self.button.setObjectName("button_" + str(z))
            self.label.setText(i[0])
            self.gridLayout.addWidget(self.button, z, 1, 1, 1)
            z += 1
        # self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        # self.label_32.setObjectName("label_32")
        # self.gridLayout.addWidget(self.label_32, 1, 0, 1, 1)
        # self.button1_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        # self.button1_7.setEnabled(False)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.button1_7.sizePolicy().hasHeightForWidth())
        # self.button1_7.setSizePolicy(sizePolicy)
        # self.button1_7.setMinimumSize(QtCore.QSize(40, 40))
        # self.button1_7.setText("")
        # self.button1_7.setObjectName("button1_7")
        # self.gridLayout.addWidget(self.button1_7, 1, 1, 1, 1)
        # self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        # self.label_34.setObjectName("label_34")
        # self.gridLayout.addWidget(self.label_34, 2, 0, 1, 1)
        # self.button1_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        # self.button1_9.setEnabled(False)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.button1_9.sizePolicy().hasHeightForWidth())
        # self.button1_9.setSizePolicy(sizePolicy)
        # self.button1_9.setMinimumSize(QtCore.QSize(40, 40))
        # self.button1_9.setText("")
        # self.button1_9.setObjectName("button1_9")
        # self.gridLayout.addWidget(self.button1_9, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(Tutmodgui)
        QtCore.QMetaObject.connectSlotsByName(Tutmodgui)

    def retranslateUi(self, Tutmodgui):
        _translate = QtCore.QCoreApplication.translate
        Tutmodgui.setWindowTitle(_translate("Tutmodgui", "Tutorenmodus"))
        self.label_2.setText(_translate(
            "Tutmodgui", "Fehlzeiten Block-Kompensationen"))
        # self.label_33.setText(_translate("Tutmodgui", "Mo, 24.12. (1)"))
        # self.label_32.setText(_translate("Tutmodgui", "Mo, 24.12. (1)"))
        # self.label_34.setText(_translate("Tutmodgui", "Mo, 24.12. (1)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tutmodgui = QtWidgets.QWidget()
    ui = Ui_Tutmodgui()
    ui.setupUi(Tutmodgui)
    Tutmodgui.show()
    sys.exit(app.exec_())
