# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BlockGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BlockKomp(object):
    def setupUi(self, BlockKomp):
        BlockKomp.setObjectName("BlockKomp")
        BlockKomp.setWindowModality(QtCore.Qt.ApplicationModal)
        BlockKomp.resize(314, 294)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\kursbuch.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BlockKomp.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(BlockKomp)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(BlockKomp)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(BlockKomp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 290, 242))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(30, 11, 30, 11)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.retranslateUi(BlockKomp)
        QtCore.QMetaObject.connectSlotsByName(BlockKomp)

    def retranslateUi(self, BlockKomp):
        _translate = QtCore.QCoreApplication.translate
        BlockKomp.setWindowTitle(_translate("BlockKomp", "Block"))
        self.label_2.setText(_translate("BlockKomp", "Fehlzeiten Block-Kompensationen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BlockKomp = QtWidgets.QWidget()
    ui = Ui_BlockKomp()
    ui.setupUi(BlockKomp)
    BlockKomp.show()
    sys.exit(app.exec_())
