# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ersteinrichtung.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ersteinrichtung(object):
    def setupUi(self, Ersteinrichtung):
        Ersteinrichtung.setObjectName("Ersteinrichtung")
        Ersteinrichtung.setWindowModality(QtCore.Qt.ApplicationModal)
        Ersteinrichtung.resize(313, 170)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\kursbuch.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ersteinrichtung.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Ersteinrichtung)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonEinrichten = QtWidgets.QPushButton(Ersteinrichtung)
        self.pushButtonEinrichten.setDefault(True)
        self.pushButtonEinrichten.setObjectName("pushButtonEinrichten")
        self.horizontalLayout.addWidget(self.pushButtonEinrichten)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(Ersteinrichtung)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.horizontalLayout.addWidget(self.pushButtonAbbrechen)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(60, -1, 60, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Ersteinrichtung)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEditKrzl = QtWidgets.QLineEdit(Ersteinrichtung)
        self.lineEditKrzl.setObjectName("lineEditKrzl")
        self.horizontalLayout_2.addWidget(self.lineEditKrzl)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Ersteinrichtung)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Ersteinrichtung)
        self.label.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Ersteinrichtung)
        QtCore.QMetaObject.connectSlotsByName(Ersteinrichtung)
        Ersteinrichtung.setTabOrder(self.lineEditKrzl, self.pushButtonEinrichten)
        Ersteinrichtung.setTabOrder(self.pushButtonEinrichten, self.pushButtonAbbrechen)

    def retranslateUi(self, Ersteinrichtung):
        _translate = QtCore.QCoreApplication.translate
        Ersteinrichtung.setWindowTitle(_translate("Ersteinrichtung", "Ersteinrichtung"))
        self.pushButtonEinrichten.setText(_translate("Ersteinrichtung", "Einrichten"))
        self.pushButtonAbbrechen.setText(_translate("Ersteinrichtung", "Abbrechen"))
        self.label_3.setText(_translate("Ersteinrichtung", "Kürzel:"))
        self.label_2.setText(_translate("Ersteinrichtung", "Zur Ersteinrichtung brauchen wir Dein Lehrer*innen-Kürzel:"))
        self.label.setText(_translate("Ersteinrichtung", "pyKursbuch - Ersteinrichtung"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ersteinrichtung = QtWidgets.QWidget()
    ui = Ui_Ersteinrichtung()
    ui.setupUi(Ersteinrichtung)
    Ersteinrichtung.show()
    sys.exit(app.exec_())
