# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FzOverview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogFzOverview(object):
    def setupUi(self, DialogFzOverview):
        DialogFzOverview.setObjectName("DialogFzOverview")
        DialogFzOverview.resize(780, 647)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\kursbuch.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogFzOverview.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(DialogFzOverview)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSchliessen = QtWidgets.QPushButton(DialogFzOverview)
        self.pushButtonSchliessen.setObjectName("pushButtonSchliessen")
        self.gridLayout.addWidget(self.pushButtonSchliessen, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(DialogFzOverview)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(DialogFzOverview)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(DialogFzOverview)
        QtCore.QMetaObject.connectSlotsByName(DialogFzOverview)

    def retranslateUi(self, DialogFzOverview):
        _translate = QtCore.QCoreApplication.translate
        DialogFzOverview.setWindowTitle(_translate("DialogFzOverview", "Fehlzeitenübersicht aktuelle*r Schüler*in"))
        self.pushButtonSchliessen.setText(_translate("DialogFzOverview", "Schließen"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogFzOverview", "Datum"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogFzOverview", "1."))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogFzOverview", "2."))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DialogFzOverview", "3."))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DialogFzOverview", "4."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DialogFzOverview", "5."))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("DialogFzOverview", "6."))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("DialogFzOverview", "7."))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("DialogFzOverview", "B 1."))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("DialogFzOverview", "B 2."))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("DialogFzOverview", "B 3."))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("DialogFzOverview", "B 4."))
        self.label.setText(_translate("DialogFzOverview", "Fehlzeitenübersicht Schueler*in vom ... bis ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogFzOverview = QtWidgets.QDialog()
    ui = Ui_DialogFzOverview()
    ui.setupUi(DialogFzOverview)
    DialogFzOverview.show()
    sys.exit(app.exec_())
