# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Syncdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Syncdialog(object):
    def setupUi(self, Syncdialog):
        Syncdialog.setObjectName("Syncdialog")
        Syncdialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Syncdialog.resize(422, 191)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\kursbuch.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Syncdialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Syncdialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Syncdialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(Syncdialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonUebernehmen = QtWidgets.QPushButton(Syncdialog)
        self.pushButtonUebernehmen.setObjectName("pushButtonUebernehmen")
        self.gridLayout.addWidget(self.pushButtonUebernehmen, 0, 0, 1, 1)
        self.pushButtonAbbrechen = QtWidgets.QPushButton(Syncdialog)
        self.pushButtonAbbrechen.setObjectName("pushButtonAbbrechen")
        self.gridLayout.addWidget(self.pushButtonAbbrechen, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 4, 1, 1, 1)
        self.lineEditPW = QtWidgets.QLineEdit(Syncdialog)
        self.lineEditPW.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditPW.setObjectName("lineEditPW")
        self.gridLayout_2.addWidget(self.lineEditPW, 2, 1, 1, 1)
        self.checkBoxSync = QtWidgets.QCheckBox(Syncdialog)
        self.checkBoxSync.setObjectName("checkBoxSync")
        self.gridLayout_2.addWidget(self.checkBoxSync, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Syncdialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditFTPS = QtWidgets.QLineEdit(Syncdialog)
        self.lineEditFTPS.setObjectName("lineEditFTPS")
        self.gridLayout_2.addWidget(self.lineEditFTPS, 1, 1, 1, 1)

        self.retranslateUi(Syncdialog)
        QtCore.QMetaObject.connectSlotsByName(Syncdialog)
        Syncdialog.setTabOrder(self.lineEditFTPS, self.lineEditPW)
        Syncdialog.setTabOrder(self.lineEditPW, self.checkBoxSync)
        Syncdialog.setTabOrder(self.checkBoxSync, self.pushButtonUebernehmen)
        Syncdialog.setTabOrder(self.pushButtonUebernehmen, self.pushButtonAbbrechen)

    def retranslateUi(self, Syncdialog):
        _translate = QtCore.QCoreApplication.translate
        Syncdialog.setWindowTitle(_translate("Syncdialog", "Dialog"))
        self.label.setText(_translate("Syncdialog", "Synchronisation einrichten"))
        self.label_3.setText(_translate("Syncdialog", "Passwort:"))
        self.pushButtonUebernehmen.setText(_translate("Syncdialog", "Übernehmen"))
        self.pushButtonAbbrechen.setText(_translate("Syncdialog", "Abbrechen"))
        self.checkBoxSync.setText(_translate("Syncdialog", "Synchronisation aktivieren"))
        self.label_2.setText(_translate("Syncdialog", "FTPS-Server-Domain:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Syncdialog = QtWidgets.QDialog()
    ui = Ui_Syncdialog()
    ui.setupUi(Syncdialog)
    Syncdialog.show()
    sys.exit(app.exec_())
